=== jsau-/http-sentry/config_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "expect": {
      "description": "An object which describes the expected result of a given check.",
      "type": "object",
      "properties": {
        "json": {
          "description": "JSON response we expect to receive.",
          "type": "object"
        },
        "regex": {
          "description": "Regex we expect the response to conform to.",
          "type": "string"
        },
        "status": {
          "description": "HTTP status code we expect to receive.",
          "type": "integer"
        },
        "text": {
          "description": "Text response we expect to receive.",
          "type": "string"
        }
      },
      "required": ["status"]
    },
    "request": {
      "description": "An object which describes a request to make when running a check.",
      "type": "object",
      "properties": {
        "body": {
          "description": "Response body to send, either as a plain string or as a JSON object.",
          "type": ["string", "object"]
        },
        "method": {
          "description": "HTTP method to use when making the request. This will default to 'get' if not specified.",
          "enum": ["get", "post", "put", "patch", "delete", "options"],
          "type": "string"
        },
        "headers": {
          "description": "Set of HTTP headers to include on the request.",
          "type": "object"
        },
        "timeout": {
          "description": "Timeout in seconds we should wait for before failing the test if no response is received.",
          "type": "number"
        },
        "url": {
          "description": "URL to make the request to.",
          "type": "string"
        }
      },
      "required": ["url"]
    },
    "webhook": {
      "description": "An object which describes a request to make after completing a check, either successfully or unsuccessfully.",
      "type": "object",
      "properties": {
        "headers": {
          "description": "Set of HTTP headers to include on the request.",
          "type": "object"
        },
        "timeout": {
          "description": "Timeout in seconds we should wait for before aborting the request if no response is received.",
          "type": "number"
        },
        "url": {
          "description": "URL to make the request to.",
          "type": "string"
        }
      },
      "required": ["url"]
    },
    "check": {
      "description": "An object which describes a check to run.",
      "properties": {
        "name": {
          "description": "Name that should help uniquely identify the check in logs, and webhook calls.",
          "type": "string"
        },
        "expect": {
          "$ref": "#/definitions/expect",
          "description": "The expected result of the check."
        },
        "request": {
          "$ref": "#/definitions/request",
          "description": "The request to make."
        }
      },
      "required": ["name", "expect", "request"],
      "type": "object"
    }
  },
  "properties": {
    "name": {
      "description": "Name that should help uniquely identify the set of all checks in logs, and webhook calls.",
      "type": "string"
    },
    "meta": {
      "description": "Additional metadata included in webhooks that can help uniquely identify the set of all checks.",
      "type": "object"
    },
    "logfile": {
      "description": "File path we should use when writing logs. If omitted the script writes to stdout.",
      "type": "string"
    },
    "checks": {
      "description": "Set of all checks to run.",
      "items": {
        "$ref": "#/definitions/check"
      },
      "type": "array"
    },
    "webhooks": {
      "description": "Set of webhooks.",
      "properties": {
        "failure": {
          "$ref": "#/definitions/webhook"
        },
        "success": {
          "$ref": "#/definitions/webhook"
        }
      },
      "type": "object"
    }
  },
  "required": ["checks"],
  "type": "object"
}

=== jsau-/http-sentry/example_config.json
{
  "name": "Test Config",
  "logfile": "./.test_log.txt",
  "meta": {
    "additional_field_one": 1,
    "additional_field_two": 2
  },
  "checks": [
    {
      "name": "JSON API Succeeds",
      "expect": {
        "status": 200,
        "json": {
          "title": "delectus aut autem",
          "id": 1,
          "userId": 1,
          "completed": false
        }
      },
      "request": {
        "url": "https://jsonplaceholder.typicode.com/todos/1"
      }
    },
    {
      "name": "JSON API Fails due to status code",
      "expect": {
        "status": 201,
        "json": {
          "title": "delectus aut autem",
          "id": 1,
          "userId": 1,
          "completed": false
        }
      },
      "request": {
        "url": "https://jsonplaceholder.typicode.com/todos/1"
      }
    },
    {
      "name": "JSON API Fails due to body",
      "expect": {
        "status": 200,
        "json": {
          "title2": "delectus aut autem",
          "id": 1,
          "userId": 1,
          "completed": false
        }
      },
      "request": {
        "url": "https://jsonplaceholder.typicode.com/todos/1"
      }
    },
    {
      "name": "Raw Text Succeeds",
      "expect": {
        "status": 200,
        "text": "Hello from Docker!\n"
      },
      "request": {
        "url": "https://raw.githubusercontent.com/docker-library/hello-world/master/greetings/hello-world.txt"
      }
    },
    {
      "name": "Raw Text Fails Due To Status Code",
      "expect": {
        "status": 201,
        "text": "Hello from Docker2!"
      },
      "request": {
        "url": "https://raw.githubusercontent.com/docker-library/hello-world/master/greetings/hello-world.txt"
      }
    },
    {
      "name": "Raw Text Fails Due To Body",
      "expect": {
        "status": 200,
        "text": "Hello from Docker44!"
      },
      "request": {
        "url": "https://raw.githubusercontent.com/docker-library/hello-world/master/greetings/hello-world.txt"
      }
    },
    {
      "name": "Regex Passes Literal Check",
      "expect": {
        "status": 200,
        "regex": "Hello from Docker!\n"
      },
      "request": {
        "url": "https://raw.githubusercontent.com/docker-library/hello-world/master/greetings/hello-world.txt"
      }
    },
    {
      "name": "Regex Fails Literal Check",
      "expect": {
        "status": 200,
        "regex": "Hello f22rom Docker!\n"
      },
      "request": {
        "url": "https://raw.githubusercontent.com/docker-library/hello-world/master/greetings/hello-world.txt"
      }
    },
    {
      "name": "Regex Passes",
      "expect": {
        "status": 200,
        "regex": "\\w+\\s\\w+\\s\\w+!\\n"
      },
      "request": {
        "url": "https://raw.githubusercontent.com/docker-library/hello-world/master/greetings/hello-world.txt"
      }
    }
  ],
  "webhooks": {
    "failure": {
      "headers": {
        "Authorization": "foo"
      },
      "timeout": 5,
      "url": "http://localhost:8080/failure"
    },
    "success": {
      "headers": {
        "Authorization": "foo"
      },
      "timeout": 5,
      "url": "http://localhost:8080/success"
    }
  }
}
